name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run:
    runs-on: ubuntu-20.04
    container: debian:testing

    steps:
      - uses: actions/checkout@v2

      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_READ_TOKEN }}@gitlab.com/ren15/software-development/tradelog_reader_rust.git
          cd tradelog_reader_rust
          git clone https://oauth2:${{ secrets.GITLAB_READ_TOKEN }}@gitlab.com/ren15/datalake/tradelog_examples.git
          git --no-pager  log | head -n 5

      - name: run
        shell: bash
        run: |
          source $HOME/.cargo/env
          rustup target add x86_64-unknown-linux-musl
          cd tradelog_reader_rust
          make run
          make run
          make diff


